#!/usr/bin/env python3
"""Migrate the release to full-instance-id keying (idempotent).

The original layout keyed flat dirs, configs, and task_list.json by the BASE
stem (`cuda_104`), but 18 stems have two instances in the 228-instance corpus:
their flat symlinks silently overwrote each other, leaving 29 instances
unreachable through the shipped task list (reviewer ar6W). Records and the
reference-timing lookup keyed off input.json's embedded task_id (also the base
stem), so the ambiguity propagated into results.

This script re-keys everything by the full instance id (= data/ dir name):
  1. data/<iid>/input.json  : task_id -> <iid> (base kept as task_id_base)
  2. benchmark/task_list.json : regenerated, 228 entries, task_id = stem = iid
  3. configs/**/*.yaml      : every `tasks:` list entry mapped base-stem -> iid
     (duplicate stems expand to BOTH instances)
Flat dirs (data/{input,prompts,testbench,references}) are regenerated by
scripts/prepare_benchmark.sh, which now keys by instance id — run it after
this script.
"""
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DATA = ROOT / "data"

manifest = json.loads((ROOT / "manifest.json").read_text())
instances = manifest["instances"] if isinstance(manifest, dict) and "instances" in manifest else manifest
iids = [e["id"] for e in instances]
assert len(iids) == len(set(iids))
print(f"manifest instances: {len(iids)}")

# base stem -> [iids]
base_map: dict[str, list[str]] = {}
for iid in iids:
    base_map.setdefault(iid.split("__")[0], []).append(iid)
dups = {b: v for b, v in base_map.items() if len(v) > 1}
print(f"base stems: {len(base_map)} (duplicated: {len(dups)})")

# -- 1. input.json task_id -> full id ---------------------------------------
n_upd = 0
for iid in iids:
    p = DATA / iid / "input.json"
    meta = json.loads(p.read_text())
    if meta.get("task_id") != iid:
        if "task_id_base" not in meta:
            meta["task_id_base"] = meta.get("task_id", iid.split("__")[0])
        meta["task_id"] = iid
        p.write_text(json.dumps(meta, indent=2) + "\n")
        n_upd += 1
print(f"input.json task_id rewritten: {n_upd}")

# -- 2. task_list.json -------------------------------------------------------
entries = []
for e in instances:
    iid = e["id"]
    d = DATA / iid
    bs = next((f for f in ("broken_start.cu", "broken_start.h", "broken_start.py") if (d / f).exists()), None)
    assert bs, iid
    entries.append({
        "task_id": iid,
        "stem": iid,
        "task_id_base": iid.split("__")[0],
        "source": "curated",
        "broken_start": {
            "code_path": f"data/{iid}/{bs}",
            "error_category": e["error_category"],
            "code_hash": e["broken_start_hash"][:16],
        },
    })
tl = {
    "_doc": "Full-instance-id keyed task list: task_id = stem = data/ dir name. "
            "Base stems are ambiguous for 18 duplicated stems; do not key by them.",
    "schema_version": "task_list/2.0-fullid",
    "n_total": len(entries),
    "entries": entries,
}
(ROOT / "benchmark" / "task_list.json").write_text(json.dumps(tl, indent=1))
print(f"benchmark/task_list.json: {len(entries)} entries")

# -- 3. configs --------------------------------------------------------------
n_cfg = n_expanded = 0
for cfg in sorted((ROOT / "configs").rglob("*.yaml")):
    s = cfg.read_text()
    m = re.search(r"(?m)^  tasks:\n((?:^  - .*\n)+)", s)
    if not m:
        continue
    old_lines = m.group(1).splitlines()
    new_ids: list[str] = []
    unknown = []
    for line in old_lines:
        t = line.strip().lstrip("- ").strip().strip('"')
        if t in base_map:              # base stem -> expand to all instances
            new_ids.extend(base_map[t])
        elif t in set(iids):           # already full id (idempotent)
            new_ids.append(t)
        else:
            unknown.append(t)          # removed instance (e.g. cuda_10) — drop
    seen = set()
    uniq = [x for x in new_ids if not (x in seen or seen.add(x))]
    block = "".join(f'  - "{x}"\n' for x in uniq)
    s2 = s[:m.start(1)] + block + s[m.end(1):]
    if s2 != s:
        cfg.write_text(s2)
        n_cfg += 1
        if len(uniq) != len(old_lines):
            n_expanded += 1
    if unknown:
        print(f"  {cfg.relative_to(ROOT)}: dropped unknown/removed stems: {unknown}")
print(f"configs rewritten: {n_cfg} (task-count changed in {n_expanded})")
print("done — now run: bash scripts/prepare_benchmark.sh")
